

/*> char                                                                                                                                                                                                                                                             <* 
 *> RUN_write             (cchar a_name [LEN_PATH])                                                                                                                                                                                                                  <* 
 *> {                                                                                                                                                                                                                                                                <* 
 *>    /+---(locals)-----------+-----------+-+/                                                                                                                                                                                                                      <* 
 *>    char        rce         =  -10;                                                                                                                                                                                                                               <* 
 *>    char        rc          =    0;                                                                                                                                                                                                                               <* 
 *>    FILE       *f           = NULL;                                                                                                                                                                                                                               <* 
 *>    int         i           =    0;                                                                                                                                                                                                                               <* 
 *>    char        x_heart     [LEN_HUND]  = "";                                                                                                                                                                                                                     <* 
 *>    char        t           [LEN_LABEL] = "";                                                                                                                                                                                                                     <* 
 *>    char        s           [LEN_LABEL] = "";                                                                                                                                                                                                                     <* 
 *>    /+---(header)-------------------------+/                                                                                                                                                                                                                      <* 
 *>    DEBUG_FILE   yLOG_enter   (__FUNCTION__);                                                                                                                                                                                                                     <* 
 *>    /+---(defense)------------------------+/                                                                                                                                                                                                                      <* 
 *>    DEBUG_FILE   yLOG_point   ("a_name"    , a_name);                                                                                                                                                                                                             <* 
 *>    --rce;  if (a_name == NULL) {                                                                                                                                                                                                                                 <* 
 *>       DEBUG_FILE   yLOG_exit    (__FUNCTION__);                                                                                                                                                                                                                  <* 
 *>       return rce;                                                                                                                                                                                                                                                <* 
 *>    }                                                                                                                                                                                                                                                             <* 
 *>    DEBUG_FILE   yLOG_info    ("a_name"    , a_name);                                                                                                                                                                                                             <* 
 *>    /+---(heartbeat)----------------------+/                                                                                                                                                                                                                      <* 
 *>    yEXEC_heartbeat (getpid (), 0, NULL, NULL, x_heart);                                                                                                                                                                                                          <* 
 *>    /+---(open file)----------------------+/                                                                                                                                                                                                                      <* 
 *>    f = fopen (a_name, "wt");                                                                                                                                                                                                                                     <* 
 *>    DEBUG_FILE   yLOG_point   ("f"         , f);                                                                                                                                                                                                                  <* 
 *>    --rce;  if (f == NULL) {                                                                                                                                                                                                                                      <* 
 *>       DEBUG_FILE   yLOG_exit    (__FUNCTION__);                                                                                                                                                                                                                  <* 
 *>       return rce;                                                                                                                                                                                                                                                <* 
 *>    }                                                                                                                                                                                                                                                             <* 
 *>    /+---(file header)--------------------+/                                                                                                                                                                                                                      <* 
 *>    fprintf (f, "#!/usr/local/bin/theia\n");                                                                                                                                                                                                                      <* 
 *>    fprintf (f, "##   %s %s\n", P_NAMESAKE, P_HERITAGE);                                                                                                                                                                                                          <* 
 *>    fprintf (f, "##   last update on å%sæ\n", x_heart);                                                                                                                                                                                                           <* 
 *>    fprintf (f, "\n");                                                                                                                                                                                                                                            <* 
 *>    /+---(read terminal)------------------+/                                                                                                                                                                                                                      <* 
 *>    for (i = 0; i < g_nrun; ++i) {                                                                                                                                                                                                                                <* 
 *>       if (i % 5 == 0)  fprintf (f, "#-epid  -back-  fg  ---ref---  st  d  ---title--------------------------------------------------------------------------------------------  t  ---terse------------  left  topp  s  l  wide  tall  z \n");   <* 
 *>       if (g_runs [i].r_winid == 0)  strcpy (t, "·");                                                                                                                                                                                                             <* 
 *>       else {                                                                                                                                                                                                                                                     <* 
 *>          ystrl4hex (g_runs [i].r_winid, t, 4, 'x', LEN_LABEL);                                                                                                                                                                                                   <* 
 *>          ystrldchg (t, '0', '·', LEN_LABEL);                                                                                                                                                                                                                     <* 
 *>          if (t [3] == '·')  t [3] = '0';                                                                                                                                                                                                                         <* 
 *>       }                                                                                                                                                                                                                                                          <* 
 *>       if (g_runs [i].r_stack == -1)  strcpy (s, " ·");                                                                                                                                                                                                           <* 
 *>       else                         sprintf (s, "%2d", g_runs [i].r_stack);                                                                                                                                                                                       <* 
 *>       fprintf (f, "%-6d  %-6.6s  %-2.2s  %-9.9s  %-2.2s  %1d  %-100.100s  %c  %-20.20s  %4d  %4d  %c  %c  %4d  %4d  %c  %6d  %-10.10s  %s \n",                                                                                                <* 
 *>             g_runs [i].r_eterm, g_runs [i].r_back , g_runs [i].r_fore , t,                                                                                                                                                                                       <* 
 *>             s               , g_runs [i].r_desk , g_runs [i].r_title, g_runs [i].r_type , g_runs [i].r_terse ,                                                                                                                                                   <* 
 *>             g_runs [i].r_left , g_runs [i].r_topp , g_runs [i].r_scrn , g_runs [i].r_locn ,                                                                                                                                                                      <* 
 *>             g_runs [i].r_wide , g_runs [i].r_tall , g_runs [i].r_size ,                                                                                                                                                                                          <* 
 *>             g_runs [i].r_use  , g_runs [i].r_pubname, g_runs [i].r_cmdline);                                                                                                                                                                                     <* 
 *>    }                                                                                                                                                                                                                                                             <* 
 *>    /+---(file footer)--------------------+/                                                                                                                                                                                                                      <* 
 *>    fprintf (f, "\n");                                                                                                                                                                                                                                            <* 
 *>    fprintf (f, "## end-of-file.  %d lines.  done, finito, completare, whimper [Ï´···\n", i);                                                                                                                                                                     <* 
 *>    /+---(close file)---------------------+/                                                                                                                                                                                                                      <* 
 *>    fflush (f);                                                                                                                                                                                                                                                   <* 
 *>    rc = fclose (f);                                                                                                                                                                                                                                              <* 
 *>    --rce;  if (rc != 0) {                                                                                                                                                                                                                                        <* 
 *>       DEBUG_FILE   yLOG_exit    (__FUNCTION__);                                                                                                                                                                                                                  <* 
 *>       return rce;                                                                                                                                                                                                                                                <* 
 *>    }                                                                                                                                                                                                                                                             <* 
 *>    /+> sync ();                                                                       <+/                                                                                                                                                                        <* 
 *>    /+---(complete)-----------------------+/                                                                                                                                                                                                                      <* 
 *>    DEBUG_FILE   yLOG_exit    (__FUNCTION__);                                                                                                                                                                                                                     <* 
 *>    /+---(complete)-----------------------+/                                                                                                                                                                                                                      <* 
 *>    return 0;                                                                                                                                                                                                                                                     <* 
 *> }                                                                                                                                                                                                                                                                <*/

